# Generated by Django 5.2.4 on 2025-08-20 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_picture',
            new_name='profile_photo',
        ),
    ]
